version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      - MONGO_USERNAME
      - MONGO_PWD
      - NODE_ENV=production


#    depends_on:
#      - db
  db:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME
        MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - type: volume
        source: dbprod
        target: /data/db
  reverse-proxy:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - api
      - db
      - client
volumes:
  dbprod:
    external: true